Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
		  vb.memory = "4096"
		  vb.cpus = 4
		end
	config.vm.define "zabbix" do |zabbix|
		config.vm.box = "cdsn/debian13"
		zabbix.vm.hostname = "zabbix7-timescale"
		zabbix.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
		zabbix.vm.network "forwarded_port", guest: 10050 , host: 10050, host_ip: "127.0.0.1"
		zabbix.vm.network "forwarded_port", guest: 10051 , host: 10051, host_ip: "127.0.0.1"
		zabbix.vm.network "forwarded_port", guest: 161 , host: 161, host_ip: "127.0.0.1"
		zabbix.vm.network "forwarded_port", guest: 162 , host: 162, host_ip: "127.0.0.1"
    end
	config.vm.provision "shell", inline: "sudo apt -y update"
  	config.vm.provision "shell", path: "scripts/timescaledb-install.sh"
	config.vm.provision "shell", path: "scripts/zabbix-install.sh"
end
